<?php require_once '../App/Models/protecao.php';include_once 'src/header.php' ?>
<div class="wrapper fadeInDown">
    <div id="formContent">
        <div class="mb-2 mt-4">
            <img src="src/img/usericon.png" id="icon" alt="User Icon">
        </div>
        <br>
        <p class="w-100 d-block h6">Seja bem-vindo</p><br>
        <a href="/cadastro" class="w-100 d-block pb-2 text-decoration-none text-secondary h6">Cadastro</a>
        <a href="/listausuarios" class="w-100 d-block pb-2 text-decoration-none text-secondary h6">Lista de usuários</a>
        <a href="/deleteuser" class="w-100 d-block pb-2 text-decoration-none text-secondary h6">Remover usuários</a>
        <a href="/edituser" class="w-100 d-block pb-2 text-decoration-none text-secondary h6">Editar usuários</a>
        <a href="/logoff" class="w-100 d-block pb-2 text-danger text-decoration-none h6">Sair</a>
    </div>
</div>
<?php include_once 'src/footer.php' ?>
