<?php require_once '../App/Models/listausuarios.php';require_once 'src/header.php' ?>
<div class="container mt-5 pt-5" >
    <a href="/admininicio" class="btn btn-outline-secondary">Voltar</a>
    <table class="table">
        <thead>
        <tr>
            <th scope="col">ID</th>
            <th scope="col">Nome</th>
            <th scope="col">Email</th>
        </tr>
        </thead>
        <tbody>
        <?php foreach($all_users as $key => $usuario){ ?>
            <tr>
                <th><?= $usuario['id'] ?></th>
                <td><?= $usuario['nome'] ?></td>
                <td><?= $usuario['email'] ?></td>
                <td>
                    <form method="post" action="/deleteuser_db">
                        <input type="hidden" name="user_id" value="<?= $usuario['id'] ?>">
                        <button type="submit" class="fas fa-trash fa-lg text-danger btn"></button>
                    </form>
                </td>
            </tr>
        <?php } ?>
        </tbody>
    </table>
</div>
<?php require_once 'src/footer.php' ?>