<?php include_once 'src/header.php' ?>
<div class="wrapper fadeInDown">
    <div id="formContent">
        <div class="mb-2 mt-4">
            <img src="src/img/usericon.png" id="icon" alt="User Icon">
        </div>
        <br>
        <form class="form-group" method="post" action="edituser_db">
            <input type="hidden" name="id" value="<?= $_POST['id'] ?>">
            <label>
                <input type="text" class="w-100" name="nome" placeholder="Nome" value="<?= $_POST['nome'] ?>">
            </label><br>
            <label>
                <input type="email" class="w-100" name="email" placeholder="Email" value="<?= $_POST['email'] ?>">
            </label><br>
            <button type="submit" class="btn btn-success w-100 mt-4">
                <span id="botao-entrar">Atualizar</span>
            </button>
        </form>
    </div>
</div>
<?php include_once 'src/footer.php' ?>